### ISSUE TITLE
ERDDAP links need to get inserted into ISO metadata from SOS or THREDDS endpoints

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/catalog-ckan#115]
We want to see all the available services listed for each dataset in the catalog.    But clearly we are not going to get an ERDDAP service endpoint in an ISO record generated by THREDDS or SOS, or get a THREDDS endpoint in an ISO record generated by ERDDAP. 

This means the WAF maintainers have some additional work to do:  they need some script or method to merge the ISO records created by these services into a single record.       Do we have such a tool?

Of course in come cases, custom scripts or methods will be needed to insert things like WMS endpoints from sci-wms or ncwms2 into records. 

Can we create a place for such scripts to live, or is there such a place already?

Here's an example from NERACOOS:  I search the catalog for "a01" buoy, and return the opendap and SOS endpoints, but not the ERDDAP tabledap endpoint at: http://www.neracoos.org/erddap/tabledap/A01_met_all.html
![2016-12-02_5-44-12](https://cloud.githubusercontent.com/assets/1872600/20832553/c5cc2086-b858-11e6-9b28-272921f1f4b8.png)

**Comment by mwengren** [comment]
NERACOOS is a good example of this.  There is in fact an ERDDAP WAF for NERACOOS registered in the Harvest Registry, but I think there are some content issues with the records generated by ERDDAP, so they are not all making it to the dev-catalog.    cc: @ebridger.  Here is the relevant link (authorized users only can view): https://registry.ioos.us/records/ZAqasedd44MsWvxeh. 

Some tool to merge services from one source or another would be nice, but nothing like that exists that I know of and it may be tricky to develop.  How do you associate datasets together, how do you identify where to copy service references from in the ISO metadata since there can be many locations, etc?  I don't know if the payoff would be great enough, seems it might require further discussion.  

In the NERACOOS case, the tabledap endpoints would be available, if the XML generated by ERDDAP were compliant.

**Comment by rsignell-usgs** [comment]
@pacioos and I were discussing this last week.   Sounds like they have some scripts to do the munging to get a single metadata record.  @pacioos, can you provide some examples?

**Comment by pacioos** [comment]
Actually, if you include ERDDAP links in your TDS catalogs as "viewer"
links, then they can get inserted by ncISO
as gmd:distributorTransferOptions. The only downside is a generic
gmd:protocol of "http" gets assigned. I then have a cron that saves the
ncISO output to a file and replaces all the ERDDAP gmd:protocol entries to
either "ERDDAP:griddap" or "ERDDAP:tabledap" depending on whether griddap
or tabledap appears in the URL.
Cheers,
John Maurer, PacIOOS

In TDS config:

<property name="viewer" value="
http://oos.soest.hawaii.edu/erddap/griddap/SWAN_Oahu_Best.graph,ERDDAP" />

https://goo.gl/esPzle

Result in ncISO:

<gmd:distributorTransferOptions>
<gmd:MD_DigitalTransferOptions>
<gmd:onLine>
<gmd:CI_OnlineResource>
<gmd:linkage>
<gmd:URL>
http://oos.soest.hawaii.edu/erddap/griddap/SWAN_Oahu_Best.graph
</gmd:URL>
</gmd:linkage>
<gmd:protocol>
<gco:CharacterString>http</gco:CharacterString>
</gmd:protocol>
<gmd:name>
<gco:CharacterString>ERDDAP</gco:CharacterString>
</gmd:name>
<gmd:description>
<gco:CharacterString>This URL provides a viewer for this dataset.
</gco:CharacterString>
</gmd:description>
<gmd:function>
<gmd:CI_OnLineFunctionCode codeList="
http://www.ngdc.noaa.gov/metadata/published/xsd/schema/resources/Codelist/gmxCodelists.xml#CI_PresentationFormCode
"codeListValue="download">download</gmd:CI_OnLineFunctionCode>
</gmd:function>
</gmd:CI_OnlineResource>
</gmd:onLine>
</gmd:MD_DigitalTransferOptions>
</gmd:distributorTransferOptions>

https://goo.gl/rPwtT0

After script converts gmd:protocol away from default of "http":

<gmd:distributorTransferOptions>
<gmd:MD_DigitalTransferOptions>
<gmd:onLine>
<gmd:CI_OnlineResource>
<gmd:linkage>
<gmd:URL>
http://oos.soest.hawaii.edu/erddap/griddap/SWAN_Oahu_Best.graph
</gmd:URL>
</gmd:linkage>
<gmd:protocol>
<gco:CharacterString>ERDDAP:griddap</gco:CharacterString>
</gmd:protocol>
<gmd:name>
<gco:CharacterString>ERDDAP</gco:CharacterString>
</gmd:name>
<gmd:description>
<gco:CharacterString>This URL provides a viewer for this dataset.
</gco:CharacterString>
</gmd:description>
<gmd:function>
<gmd:CI_OnLineFunctionCode codeList="
http://www.ngdc.noaa.gov/metadata/published/xsd/schema/resources/Codelist/gmxCodelists.xml#CI_PresentationFormCode
"codeListValue="download">download</gmd:CI_OnLineFunctionCode>
</gmd:function>
</gmd:CI_OnlineResource>
</gmd:onLine>
</gmd:MD_DigitalTransferOptions>
</gmd:distributorTransferOptions>

http://pacioos.org/metadata/swan_oahu.html

**Comment by mwengren** [comment]
Unlikely to implement this.  ERDDAP and THREDDS WAFs are managed independently by most RAs and fed into the Catalog/Registry separately, and, unless like PacIOOS they each put in place a mechanism to curate their own metadata records that merge both sources, it'll stay this way.  

Closing this since it's rather old and doesn't seem like an issue for the IOOS Catalog to solve.
